wscrm.settings:
  type: config_object
  label: 'WS CRM settings'
  mapping:
    wscrm:
      type: mapping
      mapping:
        page_title:
          type: text
          label: 'WS CRM generator page title:'
        source_text:
          type: text
          label: 'Source text for ws crm generation:'
block.settings.wscrm_block:
  type: block_settings
  label: WS CRM block'
  mapping:
    wscrm_block_settings:
      type: text
      label: 'WS CRM block settings'
